### PR TITLE
Adding some new magic to effects array

### PR DESCRIPTION
**Pull request by amandafilizola**
Great repo! Following with more later. 

Added effects:

1. Banishment
2. Greater Invisibility
3. Hex
4. Modify Memory
5. Summon Aberration
6. Telekinesis

### CODE REVIEW

**Comment by benjaminsampica** [comment]
Thanks for contributing! I have a different idea for concentration since it’s not a condition according to 5e - which I’m planning on finishing this weekend. If you would be so kind as to remove that, I’ll take the rest and push a release tonight. :)

**Comment by amandafilizola** [comment]
Removed concentration from condition array.

**Review by benjaminsampica — APPROVED** [review]

**Comment by benjaminsampica** [comment]
@amandafilizola this is now live in v1.1.0.

**Comment by amandafilizola** [comment]
Excited to use it and also the new concentration feature! Thanks!

**Pull request merged**
